require: rubocop-performance

AllCops:
  TargetRubyVersion: '2.6.3'
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - 'config/environments/*'
    - 'config/initializers/*'
    - 'config/application.rb'
    - 'config/boot.rb'
    - 'config/environment.rb'
    - 'db/migrate/*'
    - 'db/schema.rb'
    # - 'spec/**/*'
    - 'bin/*'
    - '*'
    - 'test/**/*'

Rails:
  Enabled: true

Metrics/BlockLength:
  Max: 40

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/EmptyLines:
  Enabled: true

Layout/ExtraSpacing:
  Enabled: true

Layout/IndentFirstArgument:
  Enabled: true

Layout/IndentFirstHashElement:
  Enabled: true

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true

Metrics/AbcSize:
  Max: 62

Metrics/ClassLength:
  Max: 150

Metrics/CyclomaticComplexity:
  Max: 19

Metrics/PerceivedComplexity:
  Max: 21

Style/BracesAroundHashParameters:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Enabled: true

Style/IfUnlessModifier:
  Enabled: false

# Offense count: 30
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: require_parentheses, require_no_parentheses, require_no_parentheses_except_multiline
Style/MethodDefParentheses:
  Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: Strict.
Style/NumericLiterals:
  MinDigits: 7

# Offense count: 49
# Cop supports --auto-correct.
# Configuration parameters: PreferredDelimiters.
Style/PercentLiteralDelimiters:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

# Offense count: 67
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, ConsistentQuotesInMultiline.
# SupportedStyles: single_quotes, double_quotes
Style/StringLiterals:
  Enabled: false


# Offense count: 27
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, MinSize.
# SupportedStyles: percent, brackets
Style/SymbolArray:
  Enabled: false

# Offense count: 9
# Cop supports --auto-correct.
# Configuration parameters: WordRegex.
# SupportedStyles: percent, brackets
Style/WordArray:
  EnforcedStyle: percent
  MinSize: 3

Style/GuardClause:
  Enabled: false
