name: deploy_production

on:
  push:
    branches: 
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: miloserdow/capistrano-deploy@v1.2
      with:
        target: 'production'
        deploy_key: ${{ secrets.DEPLOY_ENC_KEY }}
