name: deploy_production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.1.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY}}
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Install gems
      run: |
        gem install bundler
        bundle install --without default:development
    - name: Deploy to production
      run: bundle exec cap production deploy
