name: deploy_production

on:
  push:
    branches: 
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Start SSH agent
      run: eval "$(ssh-agent -s)"
    - name: Config SSH agent
      uses: yakuhzi/action-ssh-agent@v1
      with:
        public: ${{ secrets.SSH_PUBLIC_KEY }}
        private: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Install PostgreSQL client
      run: sudo apt-get install libpq-dev
    - name: Install gems
      run: |
        gem install bundler
        bundle install
    - name: Deploy to production
      run: bundle exec cap production deploy
