name: deploy_production

on:
  push:
    branches: 
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Install PostgreSQL client
      run: sudo apt-get install libpq-dev
    - name: Build with Rake
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    - uses: miloserdow/capistrano-deploy@v1.2
      with:
        target: 'production'
        deploy_key: ${{ secrets.DEPLOY_ENC_KEY }}
